variables:
  deploy: "true"
  deploymentScope: "Subscription"
  servicesToDeploy: cost-management-dashboard
  templateRepositoryName: ProvisioningEngineTemplates
  provisioningEnvironment: DEV
  templateType: terraform
  resourceGroupName: acceleratorsTeam-serviceProvsioning
  rgLocation: UK South
  subscriptionId: c98f771e-214d-4c3e-ac95-31fbd563bd0d
  serviceCode: DevOps
  budgetName: BudgetOnSubscriptionLevel
  budgetAmount: 100
  amountTrackingPeriod: Monthly   #Values can be "Monthly","Quarterly","Annually"
  startDate: "2023-05-01T00:00:00Z"
  endDate: "2024-05-01T00:00:00Z"
  actualThreshold: 90
  forcastThreshold: 110
  contactEmails: '"ashutosh.d.kumar@capgemini.com","test@capgemini.com"'
  azureResourceManagerConnection: genericTool-2nd
  dashboardName: Cost-Management
  subscriptionName: Visual-Studio-Enterprise-Subscription

  minimumTlsVersion: 
  skuTier: ToBeUpdatedLater
  accountType: 
  appInsightsWorkspaceName: generictooldemoaiw
  supportsHttpsTrafficOnly: 
  isShareSoftDeleteEnabled: 
  service: 
  appNamefuncappexport: 
  regionId: UK South
  shareSoftDeleteRetentionDays: 
  objectID_Spn_AdministratorId: c8806487-3bfc-4f0f-9d5f-63c020e5da94
  labIsolation: 
  adminPassword: 
  appPlanZoneRedundant: "false"
  adminLogin: 
  dailyRecurrence: 
  networkAclsBypass: 
  location: UK South
  isBlobSoftDeleteEnabled: 
  containerSoftDeleteRetentionDays: 
  skucapacity: ToBeUpdatedLater
  vnetName: ToBeUpdatedLater
  skuTierfamilyDB: ToBeUpdatedLater
  enabledForDeployment: false
  netFrameworkVersion: 
  appPlanSkuName: EP1
  enableSoftDelete: true
  databaseCollation: ToBeUpdatedLater
  appNamefuncappimport: 
  appInsightsResourceGroupName: generictoolne-rg
  roleIdMapping_Administrator: 00482a5a-887f-4fb3-b363-3b7fe8e74483
  dataClassification: 
  storageAccountName: 
  accessTier: 
  roleIdMapping_Reader: 21090545-7ca7-4776-b22c-e363652d74d2
  appserviceplan: generictooldemoappserviceplan
  devOpsLabName: 
  maxSizeBytes: ToBeUpdatedLater
  appInsightsName: generictooldemoai
  timeZoneId: 
  allowBlobPublicAccess: 
  requestedBackupStorageRedundancy: ToBeUpdatedLater
  loginSecretName: ToBeUpdatedLater
  isContainerRestoreEnabled: 
  appInsightsSubscriptionId: 135a3f71-bc38-4ae5-aa6d-f2198782853c
  databaseEdition: ToBeUpdatedLater
  objectID_Spn_ReaderId: c8806487-3bfc-4f0f-9d5f-63c020e5da94
  skuName: ToBeUpdatedLater
  allowSharedKeyAccess: 
  isHnsEnabled: 
  blobSoftDeleteRetentionDays: 
  identityType: 
  keyVaultName: ToBeUpdatedLater
  isContainerSoftDeleteEnabled: 
  regionPrefix: ToBeUpdatedLater
  storageAccountNameexport: ""
  enabledForDiskEncryption: false
  enableRbacAuthorization: true
  storageaccountresourceGroupName: generictoolne-rg
  eventTopicName: generictooleventtopic
  subnetNameFe: ToBeUpdatedLater
  storageAccountNameimport: ""
  databaseServiceObjectiveName: ToBeUpdatedLater
  passwordSecretName: ToBeUpdatedLater
  environmentName: 
  environment: 
  resourceGroup: 
  roleIdMapping_Contributor: f25e0fa2-a7c8-4377-a976-54943a77a395
  enabledForTemplateDeployment: true
  networkAclsDefaultAction: 
  softDeleteRetentionInDays: 90
  name: ToBeUpdatedLater
  criticality: 
  changeFeed: 
  applicationName: ToBeUpdatedLater
  appPlanName: generictooldemoappserviceplan
  isVersioningEnabled: 
  objectID_Spn_ContributorId: c8806487-3bfc-4f0f-9d5f-63c020e5da94
  instance: ToBeUpdatedLater
  kind: 
